### ISSUE TITLE
example use case requested as a notebook or jupyter

### ISSUE THREAD

**Issue by skr3178** [linnarsson-lab/cytograph2#1]
Hi, 

I want to use this tool. 
Unfortunately, I face problems with the earlier versions of cytograph- building it and running it. 
And this version also is a bit unclear. If there would be a notebook which shows how to install the package and an example case of running it, it would be useful. 
Thanks!

**Comment by slinnarsson** [comment]
Sorry, we are providing our pipeline source code in the interest of transparency so that people can see how we analyzed our published data. But we are not able to support it as a library (with docs, updates, installers, etc). The code may have dependencies on our local environment that will require some adaptation.
